### ISSUE TITLE
Version 2.0 not compilable

### ISSUE THREAD

**Issue by GitMoDu** [wizard97/ArduinoProcessScheduler#11]
I tried to use the 2.0 branch, as I already use RingBuffCPP in projects, but it's not working, as of now.

The method on Scheduler.h is different from the Cpp file.
const SchedulerPriorityLevel *getPLevels();

I tried fixing it blindly, but then the sketches don't run.

**Comment by wizard97** [comment]
Don't use the 2.0 branch, as it is a work in progress and as you found out has not really been tested. 

Instead use master for the latest version or get the latest release which is named 2.0, but is not the same as the 2.0 branch. I should probably rename this branch....

**Comment by GitMoDu** [comment]
Thanks, I understand it's a work-in-progress. I'm still using the main branch version, but would like move away from from RingBuff, as RingBuffCPP is awesome and this library is great.

**Comment by wizard97** [comment]
I definitely agree, I had plans to migrate to the C++ version, but I never quite finished... I would definitely accept a pull request updating this
