### ISSUE TITLE
_period variable an unsigned int instead of uint32_t

### ISSUE THREAD

**Issue by carmex** [wizard97/ArduinoProcessScheduler#18]
In Process.h, _period is defined as an unsigned int (line 326), and getPeriod() also returns an unsigned int (line 71). It should be a uint32_t, as that's what's taken in by setPeriod. On a lot of platforms an unsigned int is only going to be 16 bits and even going to a period of SERVICE_HOURLY results in an overflow so the process runs much more often than expected.

**Comment by wizard97** [comment]
Thanks for pointing this out. Feel free to submit a pull request if you were able to fix this.

**Comment by thijstriemstra** [comment]
@carmex and @wizard97 see #20
