### ISSUE TITLE
Is there a function like delay in Process?

### ISSUE THREAD

**Issue by asymt** [wizard97/ArduinoProcessScheduler#5]
I want to make a device that can play music at the same time and display lyrics on the LED，I created two Process class ,one controll play music and another controll display lyrics，how can controll delay in my Process like `delay() `

**Comment by wizard97** [comment]
Hi,

Do to the way how non-preemptive scheduling works, what you need to do is to have each process do some work, save their current state then return the CPU back to scheduler. A place where you want a delay is the perfect time for a process yield the CPU.

To do this your process would call setPeriod(delay_ms), where delay_ms is how long you want the scheduler to wait before calling your service routine again. Then the process will return (or call yield()) from the current service() routine.

A simple example would be the multi_blink example in the examples folder. Just edit the service routine:
```c++
    // Create our service routine
    virtual void service()
    {
      // If pin is on turn it off, otherwise turn it on
      _pinState = !_pinState;
      digitalWrite(_pin, _pinState);
      setPeriod(random(10, 1000)); 
    }
```
This line I added: ` setPeriod(random(10, 1000)); `, delays the next call to service() a random amount of time. This is effectively delaying.

Hope this was clear, let me know if you are still confused.

**Comment by asymt** [comment]
thanks！
so if I want to delay a process，I must save the process's work state? if the scheduler calling this process service routine again after delay，I must check the last state and start work from last state？my code like this:
`for (int x = 0; x < length; x++) 
      {
        tone(tonePin, tune[x]); 
        pause=millis();
        while(millis()<pause+400 * duration[x]); 
        noTone(tonePin);
      }
      pause=millis();
      while(millis()<pause+5000);`
in this code I need save the value of "x" before delay，is it ?
thanks very much angin!

**Comment by wizard97** [comment]
Yeah, you are correct!

An easy way to accomplish this is to make each process a state machine. Here is a simple example
```c++
typedef enum processState
{
    STATE_PLAYING_TONE,
    STATE_PAUSING
} processState_t;

class toneProcess : public process
{
private:
processState_t state;
int toneIndex;
};

``` 
your service routine would be something like this
```
 virtual void service()
    {

        switch(state)
        {
            case STATE_PLAYING_TONE:
                noTone(tonePin);
                setPeriod(duration[toneIndex++]);
                return;

            case STATE_PAUSING:
                tone(tonePin, tune[toneIndex]);
                setPeriod(duration[toneIndex]);
                break;
        }
}
```

Hope you get the idea!

**Comment by asymt** [comment]
yes, I'm get the idea! 
I have a long function or many functions in the process's service function，How can I let the program start from the last delayed position when I call the service method again after the middle delay?
Here is a simple example to illustrate my needs：
```c++
virtual void service(){
    function1();
    function2();
    function3();
}

void function1(){
    Serial.println("this is function1");
    //start delay
    setPeriod(500);
    yield();
}
```
so , How can I start from the function2 after the service method is called again after the delay?

**Comment by wizard97** [comment]
Hi,

Again it is easy using a state machine paradigm: 
```c++
typedef enum processState
{
    STATE_F1,
    STATE_F2,
    STATE_F3,
...etc
} processState_t;

class toneProcess : public process
{
        toneProcess(Scheduler &manager, ProcPriority pr, unsigned int period)
        :  Process(manager, pr, period)
        {
            state = STATE_F1;
        }

private:
processState_t state;
};
````

Then your service routine would be like
```c++
virtual void service() override {
    switch(state) {
        case STATE_F1:
            function1();
            break;
       case STATE_F2:
            function2();
            break;

       case STATE_F3:
            function3();
            break;
    }
}
```

Then just as you wrote, your functions would look like this
```c++
void function1(){
    Serial.println("this is function1");
    //start delay
    setPeriod(500);
    state = STATE_F2; //state transition to state 2
}
```

Hope this is clearer

**Comment by asymt** [comment]
Ah, I see, it's a good way! 
Finally, thank you for your patience, which makes me benefit！

**Comment by wizard97** [comment]
Glad you understand it, good luck!
